### ISSUE TITLE
Cat command issue.

### ISSUE THREAD

**Issue by akaKawasaki** [Gorialis/jishaku#103]
So essentially, when you try changing pages, the pages don't change.
if i press the reaction to get the next page, it doesn't change.

**Comment by Gorialis** [comment]
Please use the issue template next time.

If you're using jishaku 2.0 (I can't tell because you didn't fill out the issue template), the behavior of `cat` has been changed to upload the file instead. This behavior will likely be tweaked since, despite its claim to display the "whole file", Discord has actually decided to truncate at around 50000 characters:
<details>
<img src="https://user-images.githubusercontent.com/8049998/116191847-f80cf180-a767-11eb-8456-1dafdb394653.png">
</details>

If you're **not** using 2.0, then the problem lies in one of these places:
- Your reaction is not getting through (can other people see it?)
- Your bot is not seeing your reaction (do you have intents disabled?)
- Jishaku is not aware that the paginator interface is supposed to be paged (if you're seeing the bot add reactions, it should respond to those reactions as well)
- Some bug is causing the paging to not happen (setting up logging and checking your logs would help find out where this is the case, if it is this)

**Comment by akaKawasaki** [comment]
My jishaku is stuck on 1.20.

i keep updating it, but it doesnt change?
