### ISSUE TITLE
Automatically await coroutines when returned from jsk py.

### ISSUE THREAD

**Issue by Gnome-py** [Gorialis/jishaku#114]
## The Problem

Currently, forgetting an `await` from a python eval means you get a sad `<coroutine object whatever at 0xDEADBEEF>` returned and have to repeat the command but prepending an `await`

## The Ideal Solution

Adding a special case (like `discord.File` or `discord.Embed`) to await any coroutines returned, if wanting to retain the ablity to return coroutines, maybe have `return coro` work normally, but just `coro` as the last statement be awaited

## The Current Solution

Retyping the eval, prepending `await`, while hanging your head in shame...
## Summary

Add a special case to await coroutines returned from `jsk py`.

**Comment by Gorialis** [comment]
This was something that was often [requested](https://github.com/Gorialis/jishaku/pull/10#issuecomment-419712460) during the early days of Jishaku and it was something I made the explicit decision **not** to implement. This is mainly because it performs an opinionated action on the developer's behalf, and I always want everything done under Jishaku to be clear cut and intentional.

Jishaku stores the last execution result in a hidden variable called `_`, much like the REPL. If you forget to await, just do `jsk py await _` and it will finish the job for you.
