### ISSUE TITLE
No Output using jsk sh

### ISSUE THREAD

**Issue by HQGamerimkarton** [Gorialis/jishaku#122]
## Summary

If i use "jsk sh python3.9 -V" as example, i dont get any output.

## Reproduction steps

X

## Expected results

I get a Message with: "Python 3.9.4" and a white checkmark on the Context Message.

## Actual results

No Message, just a white checkmark on the Context Message.

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

- Python v3.9.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3453+g58ca9e99
- aiohttp v3.7.4.post0
- system info: Linux 5.10.52-v7l+ #1440 SMP Tue Jul 27 09:55:21 BST 2021
- Jishaku Version: 2.2.0

**Comment by Gorialis** [comment]
This is most likely a permissions issue rather than an issue with jishaku itself. Can you check if your bot is capable of sending messages in the channel you're executing this in? The necessary permissions should always be available if you execute jishaku as part of a DM with your bot, so doing that would be a good test to see whether this is just something that applies to where you're using it.

**Comment by Gorialis** [comment]
At the moment, this issue is inactionable since it lacks the information required to fix it. I'm going to assume as before that this is some kind of permissions issue since I haven't seen this be replicated elsewhere. Reopen or create a new issue if it's still a problem.
