### ISSUE TITLE
Nextcord broke my discord.py

### ISSUE THREAD

**Issue by heqds** [Gorialis/jishaku#147]
## Summary

So I was going to start switching my bot to nextcord. But then some stuff stopped working so I went back to discord.py. when I went back, some of my commands wouldn't work and when I uninstalled nextcord my bot wouldn't even start.

## Reproduction steps

When nextcord isn't installed and you had discord.py installed when installing nextcord

## Expected results

it will say "File "location of file", line, in <module>
    from discord import commands

## Actual results

I can't use 80% of my commands anymore.

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible
![image](https://user-images.githubusercontent.com/93957669/152248913-d0a40ed2-ebe3-4357-a32b-9d452c90120d.png)

**Comment by AbstractUmbra** [comment]
I don't think this is related to Jishaku at all? Perhaps you mean to contact the folks at Nextcord?

**Comment by BobDotCom** [comment]
Jishaku won't work with nextcord as they've changed the module name from "discord" to nextcord. This isn't jishaku's fault. Try using [Pycord](https://github.com/Pycord-Development/pycord) or another fork that doesn't change the namespace. I've made sure that Pycord is fully compatible with jishaku, and I use it myself.

**Comment by ooliver1** [comment]
note that the same pip command with force reinstall will also fix this for nextcord

however this has absolutely nothing to do with jishaku so I feel as though you should close this issue

**Comment by Gorialis** [comment]
This happens because pip doesn't know how to deal with direct filesystem conflicts, the install and uninstall operations just directly add and remove the relevant package information. Thus, if two packages vend the same module, installing both and then removing one will result in any overlapping file paths between the two getting removed, leaving you with a broken library. The fix for this is to uninstall both libraries and then only install one of them. Jishaku no longer automatically installs discord.py for you so this shouldn't be an issue anymore.
