### ISSUE TITLE
Unsupport discord.py v1.7.x 

### ISSUE THREAD

**Issue by tuna2134** [Gorialis/jishaku#195]
Discord api removed v7, so discord.py v1.7.x can’t use.

![5594CD8B-87B3-44DE-BD17-EDEF511233B3](https://user-images.githubusercontent.com/45692264/213599327-48f9a994-c81e-4d1d-ac4c-74d4b2b93b1a.jpeg)

**Comment by Gorialis** [comment]
There's not really any immediate reason to do this since the environments this would affect are broken regardless of whether jishaku claims it's compatible or not. A bump should probably be done at the same time as the shims being removed, and that would involve also reconsidering whether fork support is still worth it or not amongst other things. I have ideas for PaginatorInterface that might warrant the cleanup anyway, but I'm not particularly going to prioritize bumping the requirements until I hit something that justifies it, and at that point it would probably just be a straight bump to 2.1/2.2, whatever the latest is at the time.

**Comment by tuna2134** [comment]
But `discord.ui.Modal` is can use only discord.py v2, so i think you must stop support fork library.
