### ISSUE TITLE
Python 3.9.13 not supported

### ISSUE THREAD

**Issue by JDJGInc** [Gorialis/jishaku#197]
## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [ ] I have shown the entire traceback, if possible
- [ ] I have removed my token from display, if visible

**Comment by Gorialis** [comment]
Python 3.10 is now [over a year old](https://www.python.org/downloads/release/python-3100/), Python 3.9 is now in [security-fix-only](https://peps.python.org/pep-0596/#schedule) mode and [no longer comes with installers](https://www.python.org/downloads/release/python-3914/), and my usual litmus test for whether a version is "safe for the wild" is whether it's supported by Anaconda, since Anaconda versions and distributes packages that require all sorts of back-breaking C extensions and GPU modules, so if *it* manages to support a version, there is usually no reason to hold back on updating.

Since 3.10 passes this check (even if they're not quite ready to make it the default for Anaconda yet), the next release of Jishaku is going to drop <3.10 for the sake of being able to use 3.10 features freely (namely its typehinting changes and `match`, although I have no particular ideas for the latter yet). Jishaku has always tended to stick to the higher Python versions anyway (it was 3.6-only in a time where that still alienated most distros), it's only really strayed from this since I haven't had any strong reason to bump things until now.

I'd advise just updating your Python version. You should expect weird things if you're using git versions of Jishaku anyway, and the current PyPI version still supports old Python. Whenever the new release happens, it will be semver'd appropriately so you can lock if you really insist on not updating.
