### ISSUE TITLE
Question about next possible release to pypi

### ISSUE THREAD

**Issue by NightSlasher35** [Gorialis/jishaku#222]
I was wondering when a new stable version of jishaku would be uploaded to PyPI, since currently to get jsk sql you have to clone from GitHub. Any possible dates? Is there a stable version of code that I could clone from securely without getting from master? Thanks.

**Comment by Gorialis** [comment]
There's no hard date since I've been really busy lately so the cleanup and additional testing that would be needed for a release isn't done yet. Optimistically I'd like to say maybe next month, but it's still possible I might miss this target.

I don't think using the development version is out of the question in most situations anyway - you can skip having to manually clone via the method in the [README](https://github.com/Gorialis/jishaku#installing-development-versions):
```bash
pip install -U "jishaku @ git+https://github.com/Gorialis/jishaku@master"
```
If you don't have git on your system (i.e. in a docker deployment or something) you can also technically install without it via the archive but I don't recommend doing this because it leaves you without revision info:
```bash
pip install -U "jishaku @ https://github.com/Gorialis/jishaku/archive/master.zip"
```

#212 does already track release so I'll close this issue and if you have any questions or other followup you can put it over in that issue.

**Comment by NightSlasher35** [comment]
Thanks for pointing me to the issue, I did not see it.
