### ISSUE TITLE
[Tracking] import_expression doesn't function correctly in 3.12

### ISSUE THREAD

**Issue by Gorialis** [Gorialis/jishaku#228]
`import_expression` does spooky AST magic to get imports to be inlined through a specialized syntax: `module!`.

This doesn't work anymore in 3.12 due to parser changes within Python, need to think if there is a sensible solution.

**Comment by Sachaa-Thanasius** [comment]
Would you prefer fixing the upstream package or redoing the logic internally? I ask because I’ve written a [proof of concept](https://github.com/Sachaa-Thanasius/experimental/blob/master/src/__experimental__/features/_inline_import.py) that isn’t as rigorously tested as `import_expression` currently but seemingly works on 3.10-3.12 and isn’t as complex. It’s few enough lines of code that you could probably maintain your own version of the same code transformers within jishaku. I’d be willing to contribute that as well.

**Comment by Gorialis** [comment]
Jishaku was originally going to have this feature be internal anyway. The main reason why it's in another package is because at some point I rambled about what my requirements and vision for the feature was publicly, and the maintainer took it as a challenge and built it as a standalone package so that it could be reused.

Unfortunately, I don't have a good conventional means of communication with the maintainer anymore, and even back when I did they were increasingly inactive as time went on. While fixing it upstream would probably be for the best (because it would retroactively fix old jishaku versions), it's coming up on 4 years since the last `import_expression` update, so a PR to it might not even be acknowledged and I think it's safe to consider the package *unmaintained*.

I'd gladly merge any PRs that can handle the behavior on 3.12 as long as it passes the litmus test on 3.8-3.12 and doesn't break tracebacks or submodule resolution (e.g. `discord.utils!.snowflake_time` should work)

**Comment by ioistired** [comment]
Hi, I'm active again and am working on fixing this upstream.
