### ISSUE TITLE
cannot delete retained vars

### ISSUE THREAD

**Issue by bmintz** [Gorialis/jishaku#24]
## problem steps

```
jsk retain ON
jsk py x = 1
jsk py del x
```

## expected result

no output

## actual result

```
UnboundLocalError: local variable 'x' referenced before assignment
```

**Comment by Gorialis** [comment]
This is because global vars can't be `del`eted when in a local scope. I'm not sure there's much I can do about this, the alternative would be to reproduce retained data into locals, which is a pain and a dirtier method than I have currently.

For sake of mentioning, a way of removing it from the scope manually is to do `globals().pop("x")`

**Comment by bmintz** [comment]
:tada: :shipit:
