### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by bmintz** [Gorialis/jishaku#3]
On a fresh python3.6 venv I get:
```
└> command pip3 install jishaku
Collecting jishaku
Collecting discord.py>=1.0.0a1430 (from jishaku)
  Could not find a version that satisfies the requirement discord.py>=1.0.0a1430 (from jishaku) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12)
No matching distribution found for discord.py>=1.0.0a1430 (from jishaku)
```

To fix it you have to remove the line from requirements.txt manually and install discord.py before installing jishaku.

**Comment by Gorialis** [comment]
discord.py@rewrite **must** be installed through git before installing this library. This is mentioned in the [README](https://github.com/Gorialis/jishaku/blob/master/README.rst).
The cog will install fine if you do this beforehand. You do not need to edit `requirements.txt`.
You may also optionally use `pip install -r install_requires.txt`, as [install_requires](https://github.com/Gorialis/jishaku/blob/master/install_requires.txt) contains the git URL for installing the library conventionally.
This isn't included in the typical requirements.txt because PyPI does not allow you to have git dependencies.

**Comment by bmintz** [comment]
I did run `pip3 install --upgrade git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py`.
That's why I said you have to install discord.py first.

**Comment by Gorialis** [comment]
Again, this is mentioned in the README, in bold text at that.

**Comment by bmintz** [comment]
I followed the instructions in the readme to the letter and got the error I posted.

**Comment by bmintz** [comment]
Alright, so your directions are fine. I even followed them correctly. Turns out my install is just fucked. I can install it fine on a fresh venv.
