### ISSUE TITLE
Team administrator does not count as owner.

### ISSUE THREAD

**Issue by venoras** [Gorialis/jishaku#43]
You cannot use jishaku modules if a bot application is part of a team, part of the new 'Discord Developer License', as it believes that a team administrator does not count as the owner of a bot.

**Comment by Gorialis** [comment]
Jishaku uses [`Bot.is_owner`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.is_owner), the discord.py builtin supported method of determining who owns the bot.

The functionality of this function is not something I decide. It is part of the library - and thus, it producing the wrong value is a library issue - not mine.

That being said, it is not the library's fault that this fails either, strictly. It's Discord's.

Even though the teams functionality has been available for quite some time, Discord provides **no programmatical, automatic way to obtain the members of a bot's team ownership**. All Discord does is replace the "owner" with a fake user, which makes it instead fail to operate at all.

The addition of such a method is being discussed on their repository, at https://github.com/discordapp/discord-api-docs/issues/787.

Until then, the workaround that has been documented [in the jishaku documentation](https://jishaku.readthedocs.io/en/latest/cog.html#jishaku-as-a-cog) since before the teams feature even existed is to subclass your Bot with a custom `is_owner` command. This will make all owner checks library-wide accept whatever condition you set for ownership.

When the new endpoint is added, the library will be adjusted to use it and this problem will go away on its own.
