### ISSUE TITLE
GroupCogMeta overwrites the superclass's command parents

### ISSUE THREAD

**Issue by StarrFox** [Gorialis/jishaku#55]
### Summary

JishakuBase's commands are altered by GroupCogMeta when they should not
### Reproduction steps

```

from jishaku import JishakuBase
from jishaku.metacog import GroupCogMeta
from discord.ext import commands

bot = commands.Bot('!')

@commands.group()
async def not_jsk(self, ctx):
    pass

class MyJsk(JishakuBase, metaclass=GroupCogMeta, command_parent=not_jsk):
    pass

MyJsk(bot)
```
### Expected results

Should make a new cog with not_jsk as the parent of all commands
### Actual results

```
Traceback (most recent call last):
  File "/home/starrfox/bots/Discord-chan/venv/lib/python3.7/site-packages/jishaku/cog_base.py", line 494, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/home/starrfox/bots/Discord-chan/venv/lib/python3.7/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/home/starrfox/bots/Discord-chan/venv/lib/python3.7/site-packages/jishaku/repl/compilation.py", line 154, in traverse
    async for send, result in AsyncSender(func(*async_executor.args)):
  File "/home/starrfox/bots/Discord-chan/venv/lib/python3.7/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 13, in _repl_coroutine
  File "/home/starrfox/bots/Discord-chan/venv/lib/python3.7/site-packages/discord/ext/commands/cog.py", line 182, in __new__
    parent = lookup[parent.qualified_name]
KeyError: 'jishaku'
```

### Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

### System information

Discord.py:
- Python v3.7.3-final
- discord.py v1.3.0-alpha
    - discord.py pkg_resources: v1.3.0a2157+g1b9108f
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)

jishaku:
Name: jishaku
Version: 1.17.0.169
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email: None
License: MIT
Location: /home/starrfox/bots/Discord-chan/venv/lib/python3.7/site-packages
Requires: discord.py, braceexpand, import-expression, humanize

**Comment by Gorialis** [comment]
The command parent must use `@commands.group()` (a Command cannot have child commands)

**Comment by StarrFox** [comment]
Sorry forgot that when making the reproduction steps, still have the same issue when using commands.group though

**Comment by Gorialis** [comment]
Fixing this is kind of a pain. The key problem here is that `GroupCogMeta` is parenting the Commands it sees on the class, but since the implementation is not overridden, the Commands it finds are from the superclass (`JishakuBase`) and thus they get associated with the a Group owned by the subclass.

The two ways I can think of going about this while maintaining functionality are:

- Creating some kind of 'factory' for JishakuBase-like classes that each consumer should call to receive their own personal baseclass (and thus the Commands of the baseclass being parented is not much of a problem, since it is in effect owned by its subclass). This feels like a pretty bad way of doing it, because dynamically manufacturing new types at runtime makes those types hard to work with (`isinstance(x, JishakuBase)` would no longer be possible) and it feels like it fundamentally breaks the principle of using baseclasses in the first place

- Creating a more complicated generalized metaclass similar to `GroupCogMeta`, but instead of assigning the existing commands of the class to a provided parent, instead takes in the parent and defines the Jishaku standard commands. The problem with this approach is that subclass command callbacks wouldn't be able to call back to their superclass versions, since they wouldn't be part of the superclass anymore.

Overall, I think that the class redesign, while allowing for more extensibility, has caused a lot more problems than it's probably been worth. I figure I will redesign it when I have a better idea of how to do it properly.

**Comment by Gorialis** [comment]
This problem is mostly addressed by the jishaku `Feature` system in v2.
