### ISSUE TITLE
jishaku  msg object 

### ISSUE THREAD

**Issue by Dammibruh** [Gorialis/jishaku#63]
how to disable jishaku message object

**Comment by iomintz** [comment]
what do you mean?

**Comment by Walid129** [comment]
![Screenshot_20200423-081006_Discord](https://user-images.githubusercontent.com/36568916/80075211-e2a02e80-8539-11ea-9478-dc6e91cedf1c.jpg)
how to remove this kind of messages

**Comment by iomintz** [comment]
This is probably happening because you're using `await _ctx.send(...)`. Messageable.send returns a Message object, so jishaku displays it, just like any other expression. There's a shortcut for ctx.send though: `yield`. Try `yield 1` instead of `await _ctx.send(1)`. If you must use Messageable.send for whatever reason, you can do `await _author.send(…); None` for example.
