### ISSUE TITLE
Jishaku env variables not working

### ISSUE THREAD

**Issue by BobDotCom** [Gorialis/jishaku#83]
## Summary

I was making a new test bot on my mac, using this code:
```py
bot = commands.Bot(command_prefix=';',intents=discord.Intents.all(),case_insensitive=True)
os.environ['JISHAKU_NO_UNDERSCORE'] = 'True'
os.environ['JISHAKU_RETAIN'] = 'True'
bot.load_extension('jishaku')
```
However, jishaku is running without either of these options enabled. It worked on my other bot (jsk 1.20, python 3.8.5 on Linux Ubuntu) but it doesnt work on my test bot (jsk 1.20, python 3.8.2 on macOS Catalina). I've tried making them capital and lowercase, but it doesn't do anything. Also, I did reinstall jsk on both devices today.

![Image](https://media.discordapp.net/attachments/792460224866680885/792477332362362893/Screen_Shot_2020-12-26_at_1.41.11_PM.png?width=632&height=513)

## Reproduction steps

I haven't been able to run the code without this bug with this setup.

## Expected results

Jishaku no underscore and jishaku retain to work.

## Actual results

They didnt, although the env variables are working.

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [ ] I have shown the entire traceback, if possible (not needed, the traceback is as expected with this bug)
- [x] I have removed my token from display, if visible

## System information

- Jishaku Version: 1.20.0.220
- Python v3.8.2-final
- discord.py v1.6.0-alpha
    - discord.py pkg_resources: v1.5.1
- aiohttp v3.7.3
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020

**Comment by Gorialis** [comment]
If this fixes itself when you do `jsk reload jishaku`, it is almost certain that `jishaku.flags` is evaluating before you set your environment variables, for whatever reason (do you use jishaku as a module?).

In such a case, the solution is just to make sure the environment variables are set before jishaku loads. Ideally, I would recommend that you ensure this outside of Python.

The method to do this varies depending on your deployment: if you use systemd, you can do this in your service file; if you use Docker, you can pass it when you start the container up; if you use docker-compose, you could add it to your compose file; if you use Kubernetes, then you could define it within your deployment manifest; if you don't do any of these and just run directly, then maybe you could create a bootstrap script, or add it to your `~/.bash_profile`, or maybe your `screen` or `tmux` settings if you use either of those.

Ultimately, the way to solve this is going to depend on your own environment. I would like a better way to specify configuration preferences for jishaku in code for other reasons, but I've mostly been waiting on discord.py to figure out a way to establish this kind of infrastructure, because any attempt at my own solution would risk unsimplifying the loading routine from the current 'one line philosophy'.

Since there is no such infrastructure as of current, jishaku uses environment variables because it's an easily accessible and user-modifiable key-value mapping that I can guarantee is present in any system Python runs on.

There are caveats to this approach, being the order of operation (like seen here), and less granularity on what data I can accept as an configuration flag (for instance, in lieu of the current `JISHAKU_NO_UNDERSCORE`, I originally wanted to have something along the lines of `JISHAKU_REPL_PREFIX`, but an empty string for setting no prefix (`""`) is indistinguishable from it being unset on many systems, in which case I would want the default `_` prefix - a problem that would be sidestepped with a Pythonic configuration interface, since I can tell the difference).

**Comment by BobDotCom** [comment]
After some quick tests, it appears that `jsk reload jishaku` does fix it, but that doesn't really make sense to me. The `os.environ` runs before the bot loads the extension (as shown in the code I posted), so I would only expect that it would load the environment variables would be set before. It works this way on my main bot, which has essentially the same code. While that bot runs on systemd, it is not having this problem so there is no reason to change it there yet. I did have an idea though, could bot variables be used, maybe as an alternative (with the env variables still working as well)? For example if `bot.jishaku_no_underscore` was a boolean, the True or False value would be able to toggle the option as well. If not set, they would default to the current defaults.

**Comment by 12944qwerty** [comment]
Hi! I had the same problem. I have two bots. One bot works perfectly with jishaku. The other bot, unfortunately, has the same problem BobDotCom had. The environment variables aren't working. However, `jsk reload jishaku` didn't work either. It gave an error, but no traceback.

After running `jsk`, I found that the working bot has jishaku 1.19.1, dpy 1.3.4 and the other bot uses jishaku 1.20.0, dpy 1.5.1. Both use python 3.8.7.

What is happening?? Should I downgrade dpy or jishaku? What could fix this? Please let me know, thanks!
