### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by Dammibruh** [Gorialis/jishaku#88]
Hello, I've a suggestion I wanted to add it to jsk source code but I didn't understand the source code,  but anyway the suggestion is:
Having something like a flag `--catch-buffer` that's a boolean value, that catches the buffer printed to the terminal for jsk py subcommand or any commmand that runs code I found sometimes useful so I won't reconnect to the host again to get the printed results

**Comment by StarrFox** [comment]
believe this is answered in https://github.com/Gorialis/jishaku/issues/38

**Comment by Gorialis** [comment]
Jishaku doesn't redirect stdout automatically for reasons discussed in [#39](https://github.com/Gorialis/jishaku/issues/39#issuecomment-514293907).

A flag to enable such capturing behavior *might* be possible, but having it on the command seems like a clunky approach that would have parsing complications, and I don't really want it as an env flag or a switch (like retain) because it would apply to all evaluations, making it easy for the issues described to manifest if you don't make due consideration for it.

I also fear people would turn it on without understanding the implications.

As mentioned in #39, you can do this behavior of your own accord if it is truly necessary like so:
```py
with io!.StringIO() as f, contextlib!.redirect_stdout(f):
    print("hi")

    await _author.send(f.getvalue())  # send stdout contents to author
```

Otherwise, I recommend adjusting your code to not require capturing of stdout at all. It is more often than not possible to retrieve the data you need programmatically, rather than sifting the output stream.

For instance, if you're just printing to retrieve feedback on intermediate values, you can do so with `yield`:

```py
x = 1 + 2
yield f"1 + 2 = {x}"
```

Even print-heavy stdlib functions like `dis.dis` offer workarounds that allow you to print into a buffer you can report from instead, without touching stdout:
```py
with io!.StringIO() as f:  # no redirect_stdout here!
    dis!.dis(lambda x: x ** 2, file=f)
    yield f.getvalue()
```
