### ISSUE TITLE
Windows Server 2019 shell pm2 error

### ISSUE THREAD

**Issue by chaemoong** [Gorialis/jishaku#89]
## Expected results

jishaku shell -> pm2 list

## Actual results

cmd > pm2

[stderr] child_process.js:127
[stderr]   p.open(fd);
[stderr]     ^
[stderr] 
[stderr] Error: EBADF: bad file descriptor, uv_pipe_open
[stderr]     at Object._forkChild (child_process.js:127:5)
[stderr]     at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:337:30)
[stderr]     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:59:3)
[stderr]     at internal/main/run_main_module.js:7:1 {
[stderr]   errno: -4083,
[stderr]   code: 'EBADF',
[stderr]   syscall: 'uv_pipe_open'
[stderr] }

[status] Return code 1

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

Jishaku v1.20.0, discord.py 1.6.0, Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32

**Comment by Gorialis** [comment]
Given that this is a Node.JS call stack, it's pretty clear jishaku is not doing anything wrong here. jishaku correctly invokes `pm2`, and thus correctly reports the error that occurs when `pm2` fails.

I looked up the problem on their [issue tracker](https://github.com/Unitech/pm2) and it seems that it's [some kind of Windows-only problem](https://github.com/Unitech/pm2/issues/2037), and that at present [they don't know why it occurs](https://github.com/Unitech/pm2/issues/2037#issuecomment-299425712).

I'd first test if this tool works in a regular console, outside of jishaku. If it does, but doesn't work within it, it's still not an issue with jishaku (since it cannot make your subprocess work for you), but it's likely that `pm2` does something that doesn't work properly in a non-interactive shell (jishaku always uses non-interactive shells to prevent console windows popping up and disappearing whenever subprocesses launch).
